[package]
name = "bevy-boids"
version = "0.1.0"
edition = "2021"

[dependencies]
avian2d = "0.2.0"
bevy = "0.15.0"
bevy-inspector-egui = "0.28.0"
egui_dock = "0.15.0"
i-cant-believe-its-not-bsn = "0.3.0"
rand = "0.8.5"
